import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import * as grading from '../lib/grading.ts';
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const database={prepare(sql){let args=[];const q={bind(...values){args=values;return q},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}};return q},async batch(items){sqlite.exec('BEGIN');try{const r=[];for(const q of items)r.push(await q.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};
let user=null;
const files=new Map();const bucket={async put(key,bytes){files.set(key,new Uint8Array(bytes))},async get(key){const bytes=files.get(key);return bytes?{body:bytes}:null},async delete(key){files.delete(key)}};
let storage;

function route(file){const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};const req=name=>name==='@vercel/blob'?blobStub:name.includes('storage')?storage:name.includes('auth-user')?{getUser:async()=>user}:name.includes('grading')?grading:{db:()=>database};new Function('require','exports',source)(req,exports);return exports;}
const blobStub={put:async()=>({}),del:async()=>{},head:async()=>({})};
// Exercise the real readLimited(); swap only the blob-backed bucket.
storage=route('lib/storage.ts');storage={...storage,bucket:()=>bucket};
const reports=route('app/api/reports/route.ts');
const api=route('app/api/workspace/route.ts'),verify=route('app/api/verify/route.ts');
const post=(body,headers={})=>api.POST(new Request('https://certicell.test/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}));
assert.equal((await api.GET()).status,401);
user={userId:'alice',displayName:'Alice',email:'alice@example.test'};
assert.equal((await post({action:'intake'},{'sec-fetch-site':'cross-site'})).status,403);
const pack={serial:'PACK-001',customer:'Private client',batch:'BATCH-001',chemistry:'LFP',nominal:100};
let r=await post({action:'intake',packs:[pack]});assert.equal(r.status,201);const {ids:[id]}=await r.json();
assert.equal((await post({action:'intake',packs:[{...pack,serial:'PACK-002'},pack]})).status,409);
assert.equal((await (await api.GET()).json()).packs.length,1);
user={...user,userId:'bob'};assert.equal((await (await api.GET()).json()).packs.length,0);assert.equal((await post({action:'test',id})).status,404);
user={...user,userId:'alice'};assert.equal((await post({action:'issue',id,acknowledged:true})).status,409);
const upload=(packId,bytes='%PDF-1.7 test report',type='application/pdf')=>reports.POST(new Request('https://certicell.test/api/reports?pack='+packId+'&name=Private-lab.pdf',{method:'POST',headers:{'Content-Type':type},body:bytes}));
assert.equal((await upload(id,'not a pdf')).status,400);
assert.equal((await upload(id,'text','text/plain')).status,415);
let uploaded=await upload(id);assert.equal(uploaded.status,201);const report=await uploaded.json();
user={...user,userId:'bob'};assert.equal((await reports.GET(new Request('https://certicell.test/api/reports?id='+report.id))).status,404);assert.equal((await upload(id)).status,404);user={...user,userId:'alice'};
assert.equal((await reports.GET(new Request('https://certicell.test/api/reports?id='+report.id))).status,200);
const test={chargeRate:.5,dischargeRate:.5,lowerVoltage:40,upperVoltage:58.4,restMinutes:30,equipmentId:'RIG-01',calibrationDate:'2026-08-01',repetitions:'80.9,81.1',reportId:report.id,measured:81,temperature:25,resistance:12,imbalance:25,cycles:600,lab:'Private lab',reference:'LAB-001',testedAt:'2026-09-01',safety:'flagged',notes:'Private notes'};
assert.equal((await post({action:'test',id,test:{...test,reportId:'00000000-0000-4000-8000-000000000000'}})).status,400);
assert.equal((await post({action:'test',id,test:{...test,repetitions:'60,65'}})).status,400);
assert.equal((await post({action:'test',id,test:{...test,upperVoltage:30}})).status,400);
assert.equal((await post({action:'test',id,test})).status,200);assert.equal((await post({action:'issue',id,acknowledged:true})).status,409);
assert.equal((await post({action:'test',id,test:{...test,safety:'clear'}})).status,200);
assert.equal((await post({action:'issue',id})).status,400);
assert.equal((await post({action:'issue',id,acknowledged:true})).status,400);
r=await post({action:'issue',id,acknowledged:true,reviewNotes:'Reviewed report and matching repeat measurements.'});assert.equal(r.status,201);const cert=await r.json();
assert.equal((await post({action:'test',id,test})).status,409);assert.equal((await post({action:'issue',id,acknowledged:true})).status,409);
assert.equal((await upload(id)).status,409);
user=null;let v=await verify.GET(new Request('https://certicell.test/api/verify?id='+cert.id));assert.equal(v.status,200);const record=await v.json();assert.equal(record.soh,81);assert.ok(!JSON.stringify(record).includes('Private'));assert.equal(record.revoked,null);assert.equal(record.conditions.chargeRate,.5);assert.equal(record.repeatSummary.count,2);assert.equal(record.privateEvidence,null);
user={userId:'alice',displayName:'Alice',email:'alice@example.test'};const own=await (await verify.GET(new Request('https://certicell.test/api/verify?id='+cert.id))).json();assert.equal(own.privateEvidence.report.id,report.id);assert.equal(own.privateEvidence.reviewer.name,'Alice');assert.equal((await post({action:'revoke',id})).status,200);v=await verify.GET(new Request('https://certicell.test/api/verify?id='+cert.id));assert.ok((await v.json()).revoked);
sqlite.prepare('UPDATE certificates SET snapshot=? WHERE id=?').run('{}',cert.id);assert.equal((await verify.GET(new Request('https://certicell.test/api/verify?id='+cert.id))).status,409);
console.log('Workflow checks passed, including report upload, access isolation, evidence validation, repeat consistency, review requirements, locked evidence, certificate privacy, and revocation.');
