import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db} from '@/lib/db';
import {z} from 'zod';
export const dynamic='force-dynamic';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const schema=z.object({name:z.string().trim().min(2,'Enter at least two characters for your name.').max(100),company:z.string().trim().max(120).default('')}).strict();
export async function GET(){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to view your account.'},401);try{const profile=await db().prepare('SELECT name,company,created,updated FROM accounts WHERE owner=?').bind(user.userId).first();return reply({profile,identity:{email:user.email,name:user.displayName}});}catch(e){console.error('account read',e);return reply({error:'Your account could not be loaded. Please try again.'},503);}}
async function save(request:Request,edit:boolean){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to save your account.'},401);const origin=request.headers.get('origin');if(request.headers.get('sec-fetch-site')==='cross-site'||(origin&&origin!==new URL(request.url).origin))return reply({error:'Cross-site request rejected.'},403);if(!request.headers.get('content-type')?.includes('application/json'))return reply({error:'JSON required.'},415);if(Number(request.headers.get('content-length')||0)>4096)return reply({error:'Account details are too long.'},413);try{const raw=await request.text();if(raw.length>4096)return reply({error:'Account details are too long.'},413);const input=schema.parse(JSON.parse(raw)),now=new Date().toISOString();if(edit){const r=await db().prepare('UPDATE accounts SET name=?,company=?,updated=? WHERE owner=?').bind(input.name,input.company,now,user.userId).run();if(!r.meta.changes)return reply({error:'Create your CertiCell account first.'},404);}else{await db().prepare('INSERT INTO accounts (owner,name,company,created,updated) VALUES (?,?,?,?,?) ON CONFLICT(owner) DO NOTHING').bind(user.userId,input.name,input.company,now,now).run();}const profile=await db().prepare('SELECT name,company,created,updated FROM accounts WHERE owner=?').bind(user.userId).first();return reply({profile},edit?200:201);}catch(e){if(e instanceof z.ZodError)return reply({error:e.issues.map(i=>i.message).join(' ')},400);if(e instanceof SyntaxError)return reply({error:'Invalid account details.'},400);console.error('account save',e);return reply({error:'Could not save your account. Your entries have been kept; please try again.'},503);}}
export async function POST(request:Request){return save(request,false);}
export async function PATCH(request:Request){return save(request,true);}
