import {z} from 'zod';
export const intakeSchema=z.object({serial:z.string().trim().min(2).max(80),customer:z.string().trim().min(2).max(100),batch:z.string().trim().min(2).max(80),chemistry:z.enum(['LFP','NMC']),nominal:z.coerce.number().finite().positive().max(100000)});
export const testSchema=z.object({measured:z.coerce.number().finite().positive().max(100000),temperature:z.coerce.number().finite().min(15).max(35),resistance:z.coerce.number().finite().positive().max(10000),imbalance:z.coerce.number().finite().min(0).max(5000),cycles:z.coerce.number().int().min(0).max(100000),lab:z.string().trim().min(2).max(100),reference:z.string().trim().min(2).max(100),testedAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v<=new Date().toISOString().slice(0,10),'Test date cannot be in the future'),safety:z.enum(['clear','flagged']),notes:z.string().max(1500)});
export function assess(nominal:number,test:z.infer<typeof testSchema>){if(test.measured>nominal*1.05)throw new Error('Measured capacity exceeds 105% of rated capacity. Check the units and reference rating.');const soh=Math.min(100,Math.round(test.measured/nominal*1000)/10);return {soh,grade:test.safety==='flagged'||test.imbalance>100?'Hold':soh>=80?'A':soh>=70?'B':'C'};}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(n=>n.toString(16).padStart(2,'0')).join('');}

const positive=z.coerce.number().finite().positive();
export const evidenceSchema=testSchema.extend({
 chargeRate:positive.max(20),dischargeRate:positive.max(20),lowerVoltage:positive.max(2000),upperVoltage:positive.max(2000),restMinutes:z.coerce.number().finite().min(0).max(10080),
 equipmentId:z.string().trim().min(2).max(100),calibrationDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'Enter a valid calibration date'),
 repetitions:z.string().max(500).refine(v=>{const a=v.split(',').map(x=>Number(x.trim()));return a.length>=2&&a.length<=20&&v.split(',').every(x=>x.trim()!=='' )&&a.every(n=>Number.isFinite(n)&&n>0&&n<=100000)},'Enter 2–20 repeated capacities in Ah, separated by commas'),
 reportId:z.string().uuid()
}).superRefine((v,c)=>{if(v.upperVoltage<=v.lowerVoltage)c.addIssue({code:'custom',path:['upperVoltage'],message:'Upper pack voltage must exceed lower pack voltage.'});if(v.calibrationDate>v.testedAt)c.addIssue({code:'custom',path:['calibrationDate'],message:'Calibration must be on or before the test date.'});const a=v.repetitions.split(',').map(Number);if(Math.abs(a.reduce((s,n)=>s+n,0)/a.length-v.measured)>0.100001)c.addIssue({code:'custom',path:['measured'],message:'Measured capacity must match the repeat mean within 0.1 Ah.'});});
export function repeatSummary(test:any){if(!test?.repetitions)return null;const a=test.repetitions.split(',').map(Number);const mean=a.reduce((s:number,n:number)=>s+n,0)/a.length;return {count:a.length,mean:Math.round(mean*100)/100,min:Math.min(...a),max:Math.max(...a)};}
