import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db} from '@/lib/db';
import {intakeSchema,testSchema,evidenceSchema,repeatSummary,assess,digest} from '@/lib/grading';
export const dynamic='force-dynamic';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to access your workspace.'},401);try{const d=db();const [p,c,e]=await Promise.all([d.prepare('SELECT * FROM packs WHERE owner=? ORDER BY created DESC LIMIT 2000').bind(user.userId).all(),d.prepare('SELECT * FROM certificates WHERE owner=? ORDER BY issued DESC LIMIT 2000').bind(user.userId).all(),d.prepare('SELECT * FROM events WHERE owner=? ORDER BY created DESC LIMIT 30').bind(user.userId).all()]);const profile=await d.prepare('SELECT name,company FROM accounts WHERE owner=?').bind(user.userId).first<any>();return reply({packs:p.results,certificates:c.results,events:e.results,user:{name:profile?.name||user.displayName,email:user.email,company:profile?.company||'',hasProfile:!!profile}});}catch(e){console.error('workspace load',e);return reply({error:'Your workspace could not be loaded. Please try again.'},503);}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to save records.'},401);if(request.headers.get('sec-fetch-site')==='cross-site')return reply({error:'Cross-site request rejected.'},403);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return reply({error:'Invalid origin.'},403);if(!request.headers.get('content-type')?.includes('application/json'))return reply({error:'JSON required.'},415);if(Number(request.headers.get('content-length')||0)>200000)return reply({error:'Upload exceeds 200 KB.'},413);
try{const raw=await request.text();if(raw.length>200000)return reply({error:'Upload exceeds 200 KB.'},413);const body=JSON.parse(raw);const d=db(),now=new Date().toISOString(),owner=user.userId;const event=(id:string,message:string)=>d.prepare('INSERT INTO events (id,owner,pack_id,message,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),owner,id,message,now);
if(body.action==='intake'){if(!Array.isArray(body.packs)||!body.packs.length||body.packs.length>50)return reply({error:'Provide between 1 and 50 packs.'},400);const rows=body.packs.map((p:unknown)=>intakeSchema.parse(p));const ids:string[]=[];const statements:D1PreparedStatement[]=[];for(const p of rows){const id=crypto.randomUUID();ids.push(id);statements.push(d.prepare('INSERT INTO packs (id,owner,serial,customer,batch,chemistry,nominal,status,created) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,owner,p.serial,p.customer,p.batch,p.chemistry,p.nominal,'Received',now),event(id,p.serial+' received into '+p.batch));}await d.batch(statements);return reply({ids},201);}
if(typeof body.id!=='string')return reply({error:'A valid record is required.'},400);const p=await d.prepare('SELECT * FROM packs WHERE id=? AND owner=?').bind(body.id,owner).first<any>();if(!p)return reply({error:'Battery not found.'},404);
if(body.action==='test'){const test=evidenceSchema.parse(body.test),result=assess(p.nominal,test);const report=await d.prepare('SELECT id FROM reports WHERE id=? AND pack_id=? AND owner=?').bind(test.reportId,p.id,owner).first();if(!report)return reply({error:'Attach and select a lab report for this battery.'},400);const updated=await d.prepare("UPDATE packs SET test=?,soh=?,grade=?,status=? WHERE id=? AND owner=? AND status NOT IN ('Issued','Revoked')").bind(JSON.stringify(test),result.soh,result.grade,result.grade==='Hold'?'On hold':'In review',p.id,owner).run();if(!updated.meta.changes)return reply({error:'Issued records are immutable.'},409);await event(p.id,p.serial+' test results recorded').run();return reply(result);}
if(body.action==='issue'){if(p.status!=='In review'||!p.test||p.grade==='Hold')return reply({error:'Complete testing and resolve all holds before issuing.'},409);if(body.acknowledged!==true)return reply({error:'Acknowledge the pilot assessment limitations.'},400);const evidence=evidenceSchema.safeParse(JSON.parse(p.test));if(!evidence.success)return reply({error:'This record needs complete test conditions and a lab report before issuance.'},409);if(typeof body.reviewNotes!=='string'||body.reviewNotes.trim().length<10||body.reviewNotes.length>1500)return reply({error:'Add review notes of 10–1500 characters.'},400);const report=await d.prepare('SELECT id,name,digest,size FROM reports WHERE id=? AND pack_id=? AND owner=?').bind(evidence.data.reportId,p.id,owner).first();if(!report)return reply({error:'The referenced lab report is missing.'},409);const id='CC-'+crypto.randomUUID();const snapshot=JSON.stringify({serial:p.serial,chemistry:p.chemistry,nominal:p.nominal,soh:p.soh,grade:p.grade,test:JSON.parse(p.test),report,reviewer:{name:user.displayName,id:owner,notes:body.reviewNotes.trim(),reviewedAt:now},repeatSummary:repeatSummary(evidence.data),reuseSuitability:'Not assessed',protocol:'Pilot capacity assessment v0.2 — evidence collection; grading bands remain unvalidated',issued:now});const hash=await digest(snapshot);await d.batch([d.prepare("INSERT INTO certificates (id,owner,pack_id,snapshot,digest,issued) SELECT ?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM packs WHERE id=? AND owner=? AND status='In review' AND test=?)").bind(id,owner,p.id,snapshot,hash,now,p.id,owner,p.test),d.prepare("UPDATE packs SET status='Issued' WHERE id=? AND owner=? AND EXISTS (SELECT 1 FROM certificates WHERE id=?)").bind(p.id,owner,id)]);const saved=await d.prepare('SELECT id FROM certificates WHERE id=?').bind(id).first();if(!saved)return reply({error:'The test record changed. Reload and review again.'},409);await event(p.id,p.serial+' pilot certificate issued').run();return reply({id},201);}
if(body.action==='revoke'){if(p.status!=='Issued')return reply({error:'Only issued certificates can be revoked.'},409);await d.batch([d.prepare('UPDATE certificates SET revoked=? WHERE pack_id=? AND owner=? AND revoked IS NULL').bind(now,p.id,owner),d.prepare("UPDATE packs SET status='Revoked' WHERE id=? AND owner=?").bind(p.id,owner),event(p.id,p.serial+' certificate revoked')]);return reply({ok:true});}
return reply({error:'Unknown action.'},400);
}catch(e:any){if(e.name==='ZodError')return reply({error:e.issues.map((i:any)=>i.path.join('.')+': '+i.message).join('; ')},400);if(e.message?.includes('UNIQUE constraint'))return reply({error:'This serial number or certificate already exists. No duplicates were saved.'},409);if(e.message?.startsWith('Measured capacity'))return reply({error:e.message},400);if(e instanceof SyntaxError)return reply({error:'Invalid JSON.'},400);console.error('workspace write',e);return reply({error:'Could not save this change. Reload the workspace before retrying.'},503);}}
